using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Diagnostics;
using System.Web.UI.WebControls;
using System.IO;

namespace FakeNewsDetector_ASP.MasterPages
{
    public partial class Detection : System.Web.UI.Page
    {
        public int prediction;
        protected void Page_Load(object sender, EventArgs e)
        {
        }
        protected void Detect_click(object sender, EventArgs e)
        {
            var script = @"C:\Users\arsla\source\repos\FakeNewsDetector_ASP\FakeNewsDetector_ASP\Python\Detector.py";
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = @"C:\ProgramData\Anaconda3\python.exe";
            start.Arguments = string.Format("\"{0}\" \"{1}\"", script, article_tbox.Text);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    prediction = int.Parse(reader.ReadToEnd()); // Here is the result of StdOut(for example: print "test")
                    if (prediction == 0)
                    {
                        prediction = 2;
                    }
                    process.Close();
                }
            }
        }
        protected void SignUpPage_click(object sender, EventArgs e)
        {
            Response.Redirect("SignUp.aspx");
        }
        protected void LoginPage_click(object sender, EventArgs e)
        {
            Response.Redirect("Login.aspx");
        }
    }
}